baseURL = "/"
languageCode = 'en-us'
title = 'Axat Bhardwaj'
theme = 'hugo-noir'

# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  
[[params.honors]]
  institution = "Solulab Inc."
  title = "Gas Optimization"
  date = "March 2022"
  description = "Reduced a contract's gas fee by 50%, saving the client over $10,000 yearly."

[[params.honors]]
  institution = "Solulab Inc."
  title = "Employee Of the Month"
  date = "November 2021"

[[params.honors]]
  institution = "AICTE"
  title = "Vishwakarma Awards - National Level"
  date = "2019"

[[params.certifications]]
  title = "Ethereum Blockchain Developer Bootcamp With Solidity"
  company = "Udemy"
  
[[params.certifications]]
  title = "Introduction to EOSIO (Technical & Non-technical)"
  company = "EOSIO"

[[params.certifications]]
  title = "Blockchain Basics"
  company = "Coursera - University of Buffalo"

[[params.certifications]]
  title = "Metaverse Masterclass"
  company = "Udemy"
  
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
